apiVersion: ansible.konveyor.io/v1alpha1
kind: AnsiblePlaybookRun
metadata:
  name: example-ansibleplaybookrun
spec:
  # Add fields here
  ansiblePlaybook: 
    name: example-ansibleplaybook
    namespace: demo-test
  inventory: '{"all": {"hosts": "localhost"}}'
  hostCredential: '{"password": "b3BlcmF0b3I="}'
status: 
  status: pending
    
