apiVersion: ansible.konveyor.io/v1alpha1
kind: AnsiblePlaybookRun
metadata:
  name: example-ansibleplaybookrun
spec:
  # Add fields here
  ansiblePlaybook: 
    name: example-ansibleplaybook
    namespace: demo-test
  extraVars: '{"playbookName": "playbook.yaml", "repositoryType": "local", "repositoryUrl": "git"}'
  password: '{"password: abc"}'    
status: 
  status: pending
    
